common: &common
  # フォトアルバム、アルバム、などの呼称
  name: フォトアルバム
  # 画像、イメージ、フォトなどの呼称
  image_name: 画像
  
  # アルバム一覧の1ページに表示する数
  album_list_size: 5
  manage_album_list_size: 30
  
  # ポータルに表示する友だちアルバム一覧の最大数
  portal_album_list_size: 3
  
  # プロフィールに表示する友だちアルバム一覧の最大数
  profile_album_list_size: 3
  
  # アルバム画像一覧の1ページに表示する数
  image_list_size: 3
  manage_image_list_size: 30
  
  # 画像コメント一覧の1ページに表示する数
  image_comments_list_size: 5

development:
  <<: *common

testserver:
  <<: *common

testserver2:
  <<: *common
  
test:
  <<: *common

production:
  <<: *common
