common: &common
  # コミュニティ一覧に出す最大数
  community_list_size: 5
  portal_community_list_size: 3

  # コミュニティを作ったときにデフォルトで参加承認が必要かどうか
  # 数値の意味は cmm_community.rb を参照のこと
  default_join_type: 0

  # コミュニティ作成時の、デフォルトの topic_create_level
  default_topic_create_level: 10

  # メンバー一覧ページの最大数
  member_list_size: 5
  
  # manageページで一覧に出す数
  manage_community_list_size: 30
  manage_member_list_size: 30
  
development:
  <<: *common

testserver:
  <<: *common

testserver2:
  <<: *common
  
test:
  <<: *common

production:
  <<: *common

