common: &common
  magazine_list_size: 30
  # 送信処理をする区切り
  deliver_limit_size: 100
  
development:
  smtp_settings_address: mail.drecom.co.jp
  smtp_settings_port: 25
  send_from: magazine@drecom.co.jp
  # 一括追加処理をする区切り
  add_target_users_size: 10
  amanlyzer_log_path: /tmp/csv/
  amanlyzer_log_backup_path: /tmp/csv
  <<: *common

testserver:
  add_target_users_size: 1000
  <<: *common

testserver2:
  smtp_settings_address: localhost
  smtp_settings_port: 25
  add_target_users_size: 1000
  send_from: magazine@unshiu.drecom.jp
  amanlyzer_log_path: /var/accelmail/amanalyzer/result
  amanlyzer_log_backup_path: /var/accelmail/amanalyzer/result/backup
  <<: *common
  
test:
  smtp_settings_address: mail.drecom.co.jp
  smtp_settings_port: 25
  add_target_users_size: 10
  deliver_limit_size: 1
  send_from: magazine@unshiu.drecom.jp
  amanlyzer_log_path: test/file/amanlyze/
  amanlyzer_log_backup_path: test/file/amanlyze/backup/
  <<: *common

production:
  smtp_settings_address: localhost
  smtp_settings_domain: unshiu.drecom.jp
  smtp_settings_port: 25
  add_target_users_size: 1000
  send_from: magazine@unshiu.drecom.jp
  amanlyzer_log_path: /var/accelmail/amanalyzer/result
  amanlyzer_log_backup_path: /var/accelmail/amanalyzer/result/backup
  <<: *common
