common: &common
  message_list_size: 5
  manage_message_list_size: 30

development:
  <<: *common

testserver:
  <<: *common

testserver2:
  <<: *common
  
test:
  <<: *common

production:
  <<: *common
