common: &common
  history_list_size: 5
  history_file_path: public/system/pnt
  upload_file_dir: public/system/pnt_import/
  
development:
  <<: *common

testserver:
  <<: *common

testserver2:
  <<: *common
  
test:
  <<: *common

production:
  <<: *common