--- 
:backgroundrb: 
  :ip: 127.0.0.1
  :port: 11006
  :environment: development 
  :debug_log: true
  :log: foreground

:schedules:
<% require 'unshiu/plugins' %>
<% Unshiu::Plugins::ACTIVE_LIST.each do |plugin| %>
  <% plugin_path = "#{RAILS_ENV}/vender/plugins/#{plugin}/schedules.yml" %>
  <%= eval(IO.read(routes_path), binding, routes_path) if File.file?(plugin_path) %>
<% end %>